### ISSUE TITLE
state parameter in getRecordings should also accept values as an Array (in the same way meetingID and recordID)

### ISSUE THREAD

**Issue by jfederico** [mconf/bigbluebutton-api-ruby#26]
state	Optional	String	Since version 1.0 the recording has an attribute that shows a state that Indicates if the recording is [processing|processed|published|unpublished|deleted]. The parameter state can be used to filter results. It can be a set of states separate by commas. If it is not specified only the states [published|unpublished] are considered (same as in previous versions). If it is specified as “any”, recordings in all states are included.

http://docs.bigbluebutton.org/dev/api.html#getrecordings

**Comment by wpramio** [comment]
It accepts state values as an Array since version 1.8:
https://github.com/mconf/bigbluebutton-api-ruby/blob/5ad2dad9c9174dbda7a336c838c708d6f2434e2e/lib/bigbluebutton_api.rb#L474-L476
