### ISSUE TITLE
Implement updateRecordings for adding/removing/editing meta_parameters

### ISSUE THREAD

**Issue by jfederico** [mconf/bigbluebutton-api-ruby#27]
http://docs.bigbluebutton.org/dev/api.html#updaterecordings

**Comment by wpramio** [comment]
Implemented since version 1.7.0:
https://github.com/mconf/bigbluebutton-api-ruby/blob/5ad2dad9c9174dbda7a336c838c708d6f2434e2e/lib/bigbluebutton_api.rb#L503-L507
