### ISSUE TITLE
uploading multiple presentations?

### ISSUE THREAD

**Issue by nekapoor** [mconf/bigbluebutton-api-ruby#8]
Hello!

Can we upload multiple presentations to a meeting with the first one appearing and the rest available for recall if we click the icon in the bottom left of the presentation area? 

I've tried this: 

    modules = BigBlueButton::BigBlueButtonModules.new
    modules.add_presentation(:file, "#{Rails.public_path}/pdfs/GraySlides.pdf")
    modules.add_presentation(:url, "https://www.dropbox.com/s/iyc0hx6jys41sw3/Dorris_M6-Lesson11-STUDENT_MWR.pdf?dl=0")

and then creating the class with the modules parameters, but only the GraySlides pdf uploads. 

Thanks!

**Comment by daronco** [comment]
No more feedback, I'm assuming this is solved. Please reopen and add more information if it isn't.
