### ISSUE TITLE
Cannot load such file -- bigbluebutton_exception

### ISSUE THREAD

**Issue by jorgevbo** [mconf/bigbluebutton-api-ruby#9]
Hi,

I just installed bbb gem, but when run application I have exception: Cannot load such file -- bigbluebutton_exception

Main controller:
require 'bigbluebutton_api'
class MainController < ApplicationController
  def index
  end
end

Trace Log:
app/controllers/main_controller.rb:1:in `<top (required)>'
This error occurred while loading the following files:
   bigbluebutton_api
   bigbluebutton_exception

**Comment by isaacfranco** [comment]
It is a permisson problem.

root@localhost:/usr/local/rvm/gems/ruby-2.2.1@gemsetname/gems/bigbluebutton-api-ruby-1.3.0/lib# ls -lh
total 60K
-rw-rw-r-- 1 root rvm  31K Jul  8 01:54 bigbluebutton_api.rb
-rw-rw-r-- 1 root rvm 1.8K Jul  8 01:54 bigbluebutton_config_layout.rb
-rw-rw-r-- 1 root rvm 2.9K Jul  8 01:54 bigbluebutton_config_xml.rb
-rw------- 1 root rvm  224 Jul  8 01:54 bigbluebutton_exception.rb
-rw-r--r-- 1 root rvm 5.4K Jul  8 01:54 bigbluebutton_formatter.rb
-rw-rw-r-- 1 root rvm  940 Jul  8 01:54 bigbluebutton_hash_to_xml.rb
-rw-r--r-- 1 root rvm 2.3K Jul  8 01:54 bigbluebutton_modules.rb

You have to "chmod 664 bigbluebutton_exception.rb" to have it working again.

Yes, i´ve installed the gems as root and thats not recomended as well.

**Comment by daronco** [comment]
Thanks, @isaacfranco, I'm closing this.

If the problem persists, please reopen it @jorgevbo.
